### ISSUE TITLE
cannot connect to imap

### ISSUE THREAD

**Issue by landcraft** [gutmensch/docker-dmarc-report#27]
Hi there,

I'm having 2 issues getting this image working. I will focus on one of them and raise a ticket for the other.

I've used the recommended docker-compose. Here's my edited version:
```
  dmarc-report:
    image: gutmensch/dmarc-report:latest
    networks:
      - x
    hostname: dmarc-report
    container_name: dmarc-report
    depends_on:
      - dmarcdb
    environment:
      PUID: 'X'
      PGID: 'X'
      TZ: 'TZ'
      REPORT_DB_HOST: 'dmarcdb'
      REPORT_DB_PORT: '3306'
      REPORT_DB_NAME: 'dmarc_report'
      REPORT_DB_USER: 'dmarc_report'
      REPORT_DB_PASS: 'X'
      PARSER_IMAP_SERVER: 'imap.gmx.com'
      PARSER_IMAP_PORT: '993'
      PARSER_IMAP_USER: 'x'
      PARSER_IMAP_PASS: 'x'
      PARSER_IMAP_READ_FOLDER: 'Inbox'
      PARSER_IMAP_MOVE_FOLDER: 'Trash'
      PARSER_IMAP_MOVE_FOLDER_ERR: 'Trash'
    restart: unless-stopped

  dmarcdb:
    image: mariadb:10
    hostname: dmarcdb
    container_name: dmarcdb
    command: mariadb --skip-innodb-read-only-compressed
    environment:
      PUID: 'X'
      PGID: 'x'
      TZ: 'x'
      MYSQL_ROOT_PASSWORD: 'x'
      MYSQL_DATABASE: 'dmarc_report'
      MYSQL_USER: 'dmarc_report'
      MYSQL_PASSWORD: 'x'
    networks:
      - x
    restart: unless-stopped
```

Any ideas why I'm getting this error:
```
CRIT: Dmarc reports could not be parsed. Check your IMAP and MYSQL Settings.
```
